from enum import Enum


class DecisionType(str, Enum):

    RESPONDER = "RESPONDER"

    USAR_HERRAMIENTA = "USAR_HERRAMIENTA"

    CAMBIAR_ESTADO = "CAMBIAR_ESTADO"

    ESCALAR_A_HUMANO = "ESCALAR_A_HUMANO"

    FINALIZAR_CONVERSACION = "FINALIZAR_CONVERSACION"