from enum import Enum


class TipoEvento(str, Enum):

    PROSPECTO_CREADO = "PROSPECTO_CREADO"

    PROSPECTO_ACTUALIZADO = "PROSPECTO_ACTUALIZADO"

    COTIZACION_CREADA = "COTIZACION_CREADA"

    COTIZACION_ENVIADA = "COTIZACION_ENVIADA"

    COTIZACION_ACEPTADA = "COTIZACION_ACEPTADA"

    COTIZACION_RECHAZADA = "COTIZACION_RECHAZADA"

    PEDIDO_CREADO = "PEDIDO_CREADO"

    PEDIDO_ENTREGADO = "PEDIDO_ENTREGADO"

    ESTADO_PROSPECTO_ACTUALIZADO = "ESTADO_PROSPECTO_ACTUALIZADO"