"""agregar tabla uso_tokens

Revision ID: 0e3754aeb622
Revises: 683739b374f2
Create Date: 2026-08-17 23:13:38.150779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3754aeb622'
down_revision: Union[str, Sequence[str], None] = '683739b374f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uso_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospecto_id', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=30), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_salida', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_tokens_id'), 'uso_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uso_tokens_id'), table_name='uso_tokens')
    op.drop_table('uso_tokens')
    # ### end Alembic commands ###
