"""Agregar tabla historial_estados

Revision ID: 3cb5ad3cf892
Revises: bee14d977b32
Create Date: 2026-07-18 04:21:47.414762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb5ad3cf892'
down_revision: Union[str, Sequence[str], None] = 'bee14d977b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospecto_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'), nullable=False),
    sa.Column('estado_nuevo', sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    # ### end Alembic commands ###
