"""Agregar tabla productos

Revision ID: 5213bc982a19
Revises: 3cb5ad3cf892
Create Date: 2026-07-18 04:54:56.005500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5213bc982a19'
down_revision: Union[str, Sequence[str], None] = '3cb5ad3cf892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
