"""agregar google_place_id a prospectos

Revision ID: 551353f12a2b
Revises: 71cb500f8ade
Create Date: 2026-08-10 00:20:37.712306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551353f12a2b'
down_revision: Union[str, Sequence[str], None] = '71cb500f8ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospectos', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'prospectos', ['google_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospectos', type_='unique')
    op.drop_column('prospectos', 'google_place_id')
    # ### end Alembic commands ###
