"""agregar zona_busqueda y pausar_prospeccion a estado_cuenta

Revision ID: 5592045d12c2
Revises: 0e3754aeb622
Create Date: 2026-08-18 01:29:45.870405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5592045d12c2'
down_revision: Union[str, Sequence[str], None] = '0e3754aeb622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estado_cuenta', sa.Column('zona_busqueda_google_places', sa.String(length=200), nullable=True))
    # server_default explícito -- ya existe una fila (id=1) en esta
    # tabla y la columna es NOT NULL; el default de SQLAlchemy
    # (default=False) es solo del lado de Python, no alcanza filas
    # existentes.
    op.add_column('estado_cuenta', sa.Column('pausar_prospeccion', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('estado_cuenta', 'pausar_prospeccion', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estado_cuenta', 'pausar_prospeccion')
    op.drop_column('estado_cuenta', 'zona_busqueda_google_places')
    # ### end Alembic commands ###
