"""agregar referencia a productos

Revision ID: 71cb500f8ade
Revises: d9cce0c7514a
Create Date: 2026-08-08 22:35:12.558246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cb500f8ade'
down_revision: Union[str, Sequence[str], None] = 'd9cce0c7514a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('referencia', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'productos', ['referencia'])
    op.alter_column('prospectos', 'estado',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prospectos', 'estado',
               existing_type=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.drop_constraint(None, 'productos', type_='unique')
    op.drop_column('productos', 'referencia')
    # ### end Alembic commands ###
