"""convertir estado_anterior y estado_nuevo de historial_estados a varchar

Revision ID: 8f8f727f9685
Revises: 551353f12a2b
Create Date: 2026-08-10 03:55:45.290045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8f727f9685'
down_revision: Union[str, Sequence[str], None] = '551353f12a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial_estados', 'estado_anterior',
               existing_type=postgresql.ENUM('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'),
               type_=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               existing_nullable=False)
    op.alter_column('historial_estados', 'estado_nuevo',
               existing_type=postgresql.ENUM('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'),
               type_=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial_estados', 'estado_nuevo',
               existing_type=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               type_=postgresql.ENUM('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'),
               existing_nullable=False)
    op.alter_column('historial_estados', 'estado_anterior',
               existing_type=sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZADO', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False),
               type_=postgresql.ENUM('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto'),
               existing_nullable=False)
    # ### end Alembic commands ###
