"""initial_schema

Revision ID: bee14d977b32
Revises: 
Create Date: 2026-07-18 03:47:46.132533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee14d977b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('tipo_negocio', sa.Enum('PIZZERIA', 'PANADERIA', 'RESTAURANTE', 'CAFETERIA', 'HAMBURGUESERIA', 'OTRO', name='tiponegocio', native_enum=False), nullable=False),
    sa.Column('origen', sa.Enum('GOOGLE_MAPS', 'MANUAL', 'EXCEL', 'PAGINA_WEB', 'REFERIDO', 'FACEBOOK', 'INSTAGRAM', 'OTRO', name='origenprospecto', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('NUEVO', 'CONTACTADO', 'RESPONDIO', 'INTERESADO', 'COTIZACION_ENVIADA', 'NEGOCIACION', 'CLIENTE', 'DESCARTADO', name='estadoprospecto', native_enum=False), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_index(op.f('ix_prospectos_id'), 'prospectos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospectos_id'), table_name='prospectos')
    op.drop_table('prospectos')
    # ### end Alembic commands ###
