"""Agregar tabla eventos

Revision ID: d9cce0c7514a
Revises: 19d265dbb955
Create Date: 2026-07-28 04:20:08.341979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cce0c7514a'
down_revision: Union[str, Sequence[str], None] = '19d265dbb955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PROSPECTO_CREADO', 'PROSPECTO_ACTUALIZADO', 'COTIZACION_CREADA', 'COTIZACION_ENVIADA', 'COTIZACION_ACEPTADA', 'COTIZACION_RECHAZADA', 'PEDIDO_CREADO', 'PEDIDO_ENTREGADO', name='tipoevento', native_enum=False), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('origen', sa.Enum('API', 'N8N', 'WHATSAPP', 'WEB', 'SISTEMA', name='origenevento', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
